### ISSUE TITLE
Make aiozipkin work with stackdriver

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiozipkin#65]
Looks like [stackdriver-zipkin ](https://github.com/GoogleCloudPlatform/stackdriver-zipkin) does not like when `kind` is `null`

```
2017-12-29 21:26:03.741  WARN 5 --- [tp1325056130-17] zipkin.server.ZipkinHttpCollector        : Cannot decode spans due to IllegalArgumentException(Expected a string but was NULL at line 1 column 144 path $[0].kind reading List<Span2> from json: [{"traceId": "aaf6a73afc1331c969f58e8d3bad1c3a", "name": "mysql:select", "parentId": "970a503795e2f192", "id": "f3793bd84c69b83d", "kind": null, "timestamp": 1514582758614251, "duration": 10204, "debug": false, "shared": false, "localEndpoint": {"serviceName": "aiohttp_server", "ipv4": "127.0.0.1", "port": 8080}, "remoteEndpoint": null, "annotations": [], "tags": {}}, {"traceId": "aaf6a73afc1331c969f58e8d3bad1c3a", "name": "GET /api/v1/posts/0", "parentId": null, "id": "970a503795e2f192", "kind": "SERVER", "timestamp": 1514582758614171, "duration": 10433, "debug": false, "shared": true, "localEndpoint": {"serviceName": "aiohttp_server", "ipv4": "127.0.0.1", "port": 8080}, "remoteEndpoint": {"ipv4": "127.0.0.1"}, "annotations": [], "tags": {"http.path": "/api/v1/posts/0", "http.method": "GET", "http.status_code": "200"}}])

java.lang.IllegalArgumentException: Expected a string but was NULL at line 1 column 144 path $[0].kind reading List<Span2> from json: [{"traceId": "aaf6a73afc1331c969f58e8d3bad1c3a", "name": "mysql:select", "parentId": "970a503795e2f192", "id": "f3793bd84c69b83d", "kind": null, "timestamp": 1514582758614251, "duration": 10204, "debug": false, "shared": false, "localEndpoint": {"serviceName": "aiohttp_server", "ipv4": "127.0.0.1", "port": 8080}, "remoteEndpoint": null, "annotations": [], "tags": {}}, {"traceId": "aaf6a73afc1331c969f58e8d3bad1c3a", "name": "GET /api/v1/posts/0", "parentId": null, "id": "970a503795e2f192", "kind": "SERVER", "timestamp": 1514582758614171, "duration": 10433, "debug": false, "shared": true, "localEndpoint": {"serviceName": "aiohttp_server", "ipv4": "127.0.0.1", "port": 8080}, "remoteEndpoint": {"ipv4": "127.0.0.1"}, "annotations": [], "tags": {"http.path": "/api/v1/posts/0", "http.method": "GET", "http.status_code": "200"}}]
	at zipkin.internal.JsonCodec.exceptionReading(JsonCodec.java:738) ~[zipkin-1.30.2.jar!/:na]
	at zipkin.internal.JsonCodec.readList(JsonCodec.java:661) ~[zipkin-1.30.2.jar!/:na]
	at zipkin.internal.Span2JsonCodec.readSpans(Span2JsonCodec.java:48) ~[zipkin-1.30.2.jar!/:na]
	at zipkin.internal.Span2JsonDecoder.readSpans(Span2JsonDecoder.java:29) ~[zipkin-1.30.2.jar!/:na]
	at zipkin.collector.Collector.acceptSpans(Collector.java:93) ~[zipkin-1.30.2.jar!/:na]
	at zipkin.server.ZipkinHttpCollector.validateAndStoreSpans(ZipkinHttpCollector.java:99) [zipkin-server-1.30.2.jar!/:na]
	at zipkin.server.ZipkinHttpCollector.uploadSpansJson2(ZipkinHttpCollector.java:68) [zipkin-server-1.30.2.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar!/:3.1.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar!/:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) [jetty-servlet-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650) [jetty-servlet-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206) [websocket-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) [spring-boot-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110) [spring-boot-actuator-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106) [spring-boot-actuator-1.5.6.RELEASE.jar!/:1.5.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [jetty-servlet-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:454) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673) [jetty-util-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591) [jetty-util-9.4.6.v20170531.jar!/:9.4.6.v20170531]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.lang.IllegalStateException: Expected a string but was NULL at line 1 column 144 path $[0].kind
	at zipkin.internal.gson.stream.JsonReader.nextString(JsonReader.java:825) ~[zipkin-1.30.2.jar!/:na]
	at zipkin.internal.Span2JsonCodec$SimpleSpanReader.fromJson(Span2JsonCodec.java:74) ~[zipkin-1.30.2.jar!/:na]
	at zipkin.internal.Span2JsonCodec$SimpleSpanReader.fromJson(Span2JsonCodec.java:55) ~[zipkin-1.30.2.jar!/:na]
	at zipkin.internal.JsonCodec.readList(JsonCodec.java:657) ~[zipkin-1.30.2.jar!/:na]
	... 72 common frames omitted

```

**Comment by jettify** [comment]
fixed via https://github.com/aio-libs/aiozipkin/pull/66

**Comment by adriancole** [comment]
Ps this is unfortunately a maintenance thing on the stackdriver zipkin
project which updates infrequently (bug has long been fixed). We are
waiting for them to migrate the repo into openzipkin so that it can be
better maintained.
